# Generated by Django 5.1.6 on 2025-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quizprogress_random_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='current_question_answered',
            field=models.BooleanField(default=False),
        ),
    ]
